#Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada.
n = int(input("Insira um número: "))
print("{} X {} = {}".format(n, 1, n*1))
print("{} X {} = {}".format(n, 2, n*2))
print("{} X {} = {}".format(n, 3, n*3))
print("{} X {} = {}".format(n, 4, n*4))
print("{} X {} = {}".format(n, 5, n*5))
print("{} X {} = {}".format(n, 6, n*6))
print("{} X {} = {}".format(n, 7, n*7))
print("{} X {} = {}".format(n, 8, n*8))
print("{} X {} = {}".format(n, 9, n*9))
print("{} X {} = {}".format(n, 10, n*10))
